Started at: 
Mon Dec 11 17:10:18 CET 2023
instance 2
Computing answer sets
Answer set generation time: 170.06392526626587 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 0.9000000000000004
     jac: array([1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89])
Optimization time: 6.043116807937622 s
Target equation: 0.9821223500555812
Sum of optimizable facts = 0.9000000000000004
Optimal probabilities
[0.01 0.89]

real	2m57.810s
user	2m57.084s
sys	0m0.572s
instance 3
Computing answer sets
Answer set generation time: 172.24590468406677 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 0.9100000000000007
     jac: array([1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01])
Optimization time: 8.340697526931763 s
Target equation: 0.9821223500555806
Sum of optimizable facts = 0.9100000000000007
Optimal probabilities
[0.01 0.89 0.01]

real	3m2.257s
user	3m1.460s
sys	0m0.608s
instance 4
Computing answer sets
Answer set generation time: 170.91058588027954 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 1.8000000000000003
     jac: array([1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89])
Optimization time: 12.393211603164673 s
Target equation: 0.9742697970205374
Sum of optimizable facts = 1.8000000000000003
Optimal probabilities
[0.01 0.89 0.01 0.89]

real	3m4.947s
user	3m4.267s
sys	0m0.496s
instance 5
/home/dazzolin/anaconda3/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
Computing answer sets
Answer set generation time: 168.4058096408844 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 1.810000000000001
     jac: array([1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01])
Optimization time: 19.37243676185608 s
Target equation: 0.9742697970205375
Sum of optimizable facts = 1.810000000000001
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01]

real	3m9.480s
user	3m8.801s
sys	0m0.491s
instance 6
Computing answer sets
Answer set generation time: 173.5821385383606 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 2.7000000000000046
     jac: array([1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89])
Optimization time: 28.941178798675537 s
Target equation: 0.9672104311607729
Sum of optimizable facts = 2.7000000000000046
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89]

real	3m24.203s
user	3m23.417s
sys	0m0.606s
instance 7
/home/dazzolin/anaconda3/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
Computing answer sets
Answer set generation time: 167.6037995815277 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 2.7100000000000004
     jac: array([1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01])
Optimization time: 44.77899169921875 s
Target equation: 0.9672104311607734
Sum of optimizable facts = 2.7100000000000004
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01]

real	3m34.102s
user	3m33.309s
sys	0m0.604s
instance 8
Computing answer sets
Answer set generation time: 163.6484386920929 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 3.600000000000003
     jac: array([1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89])
Optimization time: 69.2434024810791 s
Target equation: 0.9608641325595589
Sum of optimizable facts = 3.600000000000003
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89]

real	3m54.577s
user	3m53.787s
sys	0m0.570s
instance 9
Computing answer sets
Answer set generation time: 164.89604377746582 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 3.610000000000005
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01])
Optimization time: 101.26528835296631 s
Target equation: 0.960864132559559
Sum of optimizable facts = 3.610000000000005
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01]

real	4m28.081s
user	4m27.097s
sys	0m0.629s
instance 10
/home/dazzolin/anaconda3/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
Computing answer sets
Answer set generation time: 165.92247223854065 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 4.5
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89])
Optimization time: 142.97280740737915 s
Target equation: 0.9551588742211021
Sum of optimizable facts = 4.5
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89]

real	5m10.894s
user	5m9.682s
sys	0m0.725s
instance 11
/home/dazzolin/anaconda3/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
Computing answer sets
Answer set generation time: 167.3748209476471 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 4.5100000000000025
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01])
Optimization time: 210.54055428504944 s
Target equation: 0.955158874221102
Sum of optimizable facts = 4.5100000000000025
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01]

real	6m19.800s
user	6m18.675s
sys	0m0.702s
instance 12
Computing answer sets
Answer set generation time: 159.46618938446045 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 5.400000000000019
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01,
       0.89])
Optimization time: 293.8920569419861 s
Target equation: 0.9500299046037122
Sum of optimizable facts = 5.400000000000019
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89]

real	7m35.431s
user	7m34.046s
sys	0m0.763s
instance 13
/home/dazzolin/anaconda3/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
Computing answer sets
Answer set generation time: 157.109445810318 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 5.409999999999999
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01,
       0.89, 0.01])
Optimization time: 406.7631404399872 s
Target equation: 0.9500299046037148
Sum of optimizable facts = 5.409999999999999
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01]

real	9m25.995s
user	9m24.417s
sys	0m0.842s
instance 14
/home/dazzolin/anaconda3/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
Computing answer sets
Answer set generation time: 160.40980911254883 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 6.299999999999999
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01,
       0.89, 0.01, 0.89])
Optimization time: 574.0737097263336 s
Target equation: 0.945419012725437
Sum of optimizable facts = 6.299999999999999
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89]

real	12m16.664s
user	12m14.904s
sys	0m0.911s
instance 15
Computing answer sets
Answer set generation time: 155.91505527496338 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 6.310000000000048
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01,
       0.89, 0.01, 0.89, 0.01])
Optimization time: 846.693286895752 s
Target equation: 0.9454190127254255
Sum of optimizable facts = 6.310000000000048
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89
 0.01]

real	16m44.637s
user	16m42.667s
sys	0m0.942s
instance 16
/home/dazzolin/anaconda3/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
Computing answer sets
Answer set generation time: 154.82177591323853 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 7.20000000000001
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01,
       0.89, 0.01, 0.89, 0.01, 0.89])
Optimization time: 1024.9376292228699 s
Target equation: 0.941273867501531
Sum of optimizable facts = 7.20000000000001
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89
 0.01 0.89]

real	19m42.014s
user	19m39.717s
sys	0m1.025s
instance 17
Computing answer sets
Answer set generation time: 142.22968816757202 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 7.210000000000013
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01,
       0.89, 0.01, 0.89, 0.01, 0.89, 0.01])
Optimization time: 1409.1093258857727 s
Target equation: 0.94127386750153
Sum of optimizable facts = 7.210000000000013
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89
 0.01 0.89 0.01]

real	25m53.772s
user	25m50.759s
sys	0m1.348s
instance 18
Computing answer sets
Answer set generation time: 145.9242649078369 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 8.10000000000003
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01,
       0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89])
Optimization time: 1890.2746546268463 s
Target equation: 0.937547423815385
Sum of optimizable facts = 8.10000000000003
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89
 0.01 0.89 0.01 0.89]

real	33m58.726s
user	33m55.650s
sys	0m1.147s
instance 19
/home/dazzolin/anaconda3/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
Computing answer sets
Answer set generation time: 148.96188282966614 s
number of sums: 2046
number of prods: 38893
Starting optimization
     fun: 8.11000000000001
     jac: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 2
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01,
       0.89, 0.01, 0.89, 0.01, 0.89, 0.01, 0.89, 0.01])
Optimization time: 2487.501846075058 s
Target equation: 0.9375474238154005
Sum of optimizable facts = 8.11000000000001
Optimal probabilities
[0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89 0.01 0.89
 0.01 0.89 0.01 0.89 0.01]

real	43m59.127s
user	43m55.262s
sys	0m1.367s
Ended at: 
Mon Dec 11 20:39:00 CET 2023
